### ISSUE TITLE
[v2.1.3] Debug logging not written to console

### ISSUE THREAD

**Issue by Dids** [dev-tavern/vue-logger-plugin#18]
Using Vue 3 and v2.1.3 of `vue-logger-plugin`, I've setup the logger like so:
```ts
...
import { createLogger } from 'vue-logger-plugin'
...
const logger = createLogger({
  enabled: true,
  level: 'debug',
  consoleEnabled: true,
})
...
app.use(logger)
```

I can call the `logger` instance directly after creating it, which works fine:
```ts
logger.log('log')
logger.debug('debug')
logger.info('info')
logger.warn('warn')
logger.error('error')
```

However, no matter if I set the log level to `debug` manually or let it use the defaults, `logger.debug()` calls will never end up in the console. Same when called from components, eg `this.$log.debug()`.

Is this by design or perhaps a bug? Or am I somehow using this plugin wrong?

**Comment by Dids** [comment]
Never mind. Apparently the logger defines `debug` as `verbose`, which means it won't be available in browser developer tools by default.

Explains why I missed it, but closing the issue as this is resolved. Thank you for the plugin!

**Comment by joshuagamble** [comment]
You are correct, and it may be labeled differently between certain browsers.  I believe Firefox labels it as `debug` level but Chrome labels the same as `verbose` level.

Good to hear you figured it out, thanks for using the plugin!

**Comment by joekaiser** [comment]
Can this information be added to the README?

**Comment by joshuagamble** [comment]
A note regarding this has been added to the README.  Thanks for the suggestion, @joekaiser.

**Comment by ajmas** [comment]
I ran into this today. The code was correct with 'debug', but Chrome didn't have 'verbose' selected as part of default levels, in the console. Sharing this for anyone else who runs into this issue:

<img width="236" alt="Screenshot 2023-08-04 at 14 44 59" src="https://github.com/dev-tavern/vue-logger-plugin/assets/682269/4075b610-e395-46cf-b739-46c180779100">

You'll see if you click 'default', then 'verbose' becomes unchecked.
