### ISSUE TITLE
the develop-v1 when vue loaded by cdn i got an error

### ISSUE THREAD

**Issue by wind007** [dev-tavern/vue-logger-plugin#33]
the develop-v1 when vue loaded by cdn i got an error
![image](https://user-images.githubusercontent.com/13992069/174921179-aa0693a5-110e-4162-963b-bb00a769d502.png)
![image](https://user-images.githubusercontent.com/13992069/174921223-7da55e6e-b3aa-406c-baf1-9e075c9b1b63.png)

which is i use with a wrong way or the code bug?

**Comment by joshuagamble** [comment]
@wind007 Thanks for bringing this to my attention.

This was a bug within the plugin's auto-installation attempt when Vue is loaded via CDN.  I've removed this part of the code as it would never have worked appropriately.  When Vue is loaded via CDN, you can still install the plugin as normal (e.g. `Vue.use(VueLogger)`).

You can try out the fix by installing the next version 1.2.3:  `npm i vue-logger-plugin@1.2.3`

**Comment by wind007** [comment]
thanks very much
